language: node_js

node_js:
  - "12.18.3"

services:
  - docker

before_install:
  - docker build -t vjekobabic/franu .

#script:

after_success:
  - docker build -t vjekobabic/franu .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vjekobabic/franu

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Franu-env"
  env: "FranuEnv-env"
  bucket_name: $AWS_S3_BUCKET
  bucket_path: "franu"
  on:
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

after_deploy:
  - echo "Application Deployed!"
