/**
 * Every translation page object (ect. '/about-us') should include common object.
 * Common object contains locales for strings that every page should use.
 */
export const common = {
    aboutUs: 'About Us',
    contact: 'Contact',
    howItWorks: 'How it works',
    home: 'Home',
    impressum: 'Impressum',
    privacy: 'Privacy',
    termsAndConditions: 'Terms and conditions',
    termsAndConditionsClaim: 'I have read and agreed to the Franu <a href="/terms-and-conditions" style="font-weight: bold;color: #597AA8">Terms and Conditions</a> and <a href="/terms-and-conditions#privacy-policy" style="font-weight: bold;color: #597AA8">Privacy Policy</a>.',
    firstName: 'First Name',
    lastName: 'Last Name',
    eMail: 'E-mail',
    address: 'Address',
    number: 'Number',
    zip: 'ZIP',
    city: 'City',
    message: 'Message',
    phone: 'Phone',
    send: 'Send',
    next: 'Next',
    prev: 'Prev',
    kitchen: 'Kitchen',
    lKitchen: 'L kitchen',
    uKitchen: 'U kitchen',
    galleyKitchen: 'Galley kitchen',
    islandKitchen: 'Island kitchen',
    oneWallKitchen: 'One wall kitchen',
    oven: 'Oven',
    cookerHob: 'Cooker hob',
    dishwasher: 'Dishwasher',
    exhaustHood: 'Exhaust hood',
    fridge: 'Fridge',
    microwave: 'Microwave',
    coffeMachine: 'Coffe machine',
    morePhotos: 'More photos',
    munich: 'Munich',
    confirm: 'Confirm',
    locationDisclaimer: 'At the moment Franu is providing its services only for Munich area.',
    cookies: {
        cookiesTitle: 'Franu Cookies',
        acceptAll: 'Accept all',
        cookieSettings: 'Cookie settings',
        disclaimer: 'Franu uses cookies to improve your experience and measure your interaction on our web site. If you agree with that click "Accept all". To change your preferences, click "cookie settings". To find more information about our cookies visit our <a href="/terms-and-conditions#privacy-policy" style="font-weight: bold;color: #597AA8">privacy policy</a> page.',
        necessary: "Necessary",
        necessaryDescription: "These cookies are necessary for our web page in order to function properly. There for they can not be disabled",
        statistics: "Statistics",
        statisticsDescription: "These cookies helps us to understand our visitors better, so we are able to provide you better content and best experience."
    }
}
